// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe_O57ldvoS7FYUSi6M5OUcJL-3LTbPx0',
    appId: '1:39030549834:web:45c4d176a1a989dbe1a5b3',
    messagingSenderId: '39030549834',
    projectId: 'flutter-projects-fb81f',
    authDomain: 'flutter-projects-fb81f.firebaseapp.com',
    storageBucket: 'flutter-projects-fb81f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQj2A7vxY25GRhWjGGsWBu50D4gv0x204',
    appId: '1:39030549834:android:1912729b2c65bb09e1a5b3',
    messagingSenderId: '39030549834',
    projectId: 'flutter-projects-fb81f',
    storageBucket: 'flutter-projects-fb81f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATF9wyg-7_CZdEsTGFKhfd1sHsrQsU29o',
    appId: '1:39030549834:ios:139ffaa3b01910bee1a5b3',
    messagingSenderId: '39030549834',
    projectId: 'flutter-projects-fb81f',
    storageBucket: 'flutter-projects-fb81f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe_O57ldvoS7FYUSi6M5OUcJL-3LTbPx0',
    appId: '1:39030549834:web:99251fae50857e08e1a5b3',
    messagingSenderId: '39030549834',
    projectId: 'flutter-projects-fb81f',
    authDomain: 'flutter-projects-fb81f.firebaseapp.com',
    storageBucket: 'flutter-projects-fb81f.appspot.com',
  );
}
